// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQaPSdu5pcRnD43WPM8ZAeq-eNs6zJO9U',
    appId: '1:874543416631:web:5e5d69e946ec3a75bf46b2',
    messagingSenderId: '874543416631',
    projectId: 's3-projectdghabit',
    authDomain: 's3-projectdghabit.firebaseapp.com',
    storageBucket: 's3-projectdghabit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwx_Sjxnb_03bjGwBmkXg1G8ARy85Agbc',
    appId: '1:874543416631:android:2638a3e6d3b652ddbf46b2',
    messagingSenderId: '874543416631',
    projectId: 's3-projectdghabit',
    storageBucket: 's3-projectdghabit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxFtUuY_VH0Xh-2w_gwfeMhuJ3gnVBOOU',
    appId: '1:874543416631:ios:e1a0a06a90eb021bbf46b2',
    messagingSenderId: '874543416631',
    projectId: 's3-projectdghabit',
    storageBucket: 's3-projectdghabit.firebasestorage.app',
    iosBundleId: 'com.example.dghabit',
  );
}
