// lib/main.dart
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'firebase_options.dart'; // Generated by FlutterFire
import 'screens/auth_gate.dart';
import 'screens/splash_screen.dart';
import 'screens/onboarding_screen.dart';
import 'theme/app_theme.dart';
import 'providers/app_providers.dart';
import 'services/background_tasks.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  // Initialize background task scheduler (Android) and schedule from saved prefs
  // Initialize background worker on Android and schedule from saved prefs
  await initWorkmanager();
  await ensureScheduledFromPrefs();
  runApp(const ProviderScope(child: DgHabitApp()));
}

class DgHabitApp extends ConsumerWidget {
  const DgHabitApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final mode = ref.watch(themeModeProvider);
    return MaterialApp(
      title: 'dgHabit',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light(),
      darkTheme: AppTheme.dark(),
      themeMode: mode,
      home: const SplashScreen(),
      onGenerateRoute: (settings) {
        if (settings.name == '/auth') {
          return PageRouteBuilder(
            pageBuilder: (_, __, ___) => const AuthGate(),
            transitionsBuilder: (_, anim, __, child) => FadeTransition(opacity: anim, child: child),
            transitionDuration: const Duration(milliseconds: 450),
          );
        }
        if (settings.name == '/onboarding') {
          return PageRouteBuilder(
            pageBuilder: (_, __, ___) => const OnboardingScreen(),
            transitionsBuilder: (_, anim, __, child) => FadeTransition(opacity: anim, child: child),
            transitionDuration: const Duration(milliseconds: 450),
          );
        }
        return null;
      },
    );
  }
}
